### PR TITLE
CMakeLists: Add install rules

### PR DESCRIPTION
**Pull request by abouvier**
This project cannot be easily packaged without these install rules.

### CODE REVIEW

**Comment by MerryMage** [comment]
I don't understand the need to change the include directory structure.

**Comment by abouvier** [comment]
What do you mean "change"? :p
It's packaging related, using `cmake --install`: https://aur.archlinux.org/packages/dynarmic-git/
I need to copy `frontend/A32/translate/translate_callbacks.h` because this file is included by `interface/A32/config.h` (and `common/common_types.h` is include by `translate_callbacks.h`). This is weird because these two files do not seem to be part of the interface.

**Comment by abouvier** [comment]
I also added CMake config files needed to use `find_package(dynarmic)` in other projects.

**Comment by Tachi107** [comment]
I believe that this PR can be closed, as #652 has been merged

**Pull request closed without merging**
