### PR TITLE
interface: allow clear of previously-signaled halt

### PR DESCRIPTION
**Pull request by liamwhite**
In yuzu, interrupts are often signaled at any time, even when Dynarmic is not running. This causes Dynarmic to needlessly break out of execution before running any code, even after an interrupt has been cleared. By clearing the interrupt in Dynarmic too this case is avoided.

### CODE REVIEW

**Comment by merryhime** [comment]
I feel allowing this leads to being able to accidentally write incorrect multithreaded code too easily.
I set a `HaltExecution`, and I know execution will halt in the future (whether it be during a current `Run`, or in a future `Run`), and I know that the return value of `Run` will definitely have the bit set.

This would can easily lead to races between `HaltExecution` and `ClearHalt` on separate threads, or for `ClearHalt` to be sequenced between a `cmp` and `xchg` of `halt_reason`.

**Comment by liamwhite** [comment]
Would a HaltExecutionIfRunning API be better here?

**Comment by merryhime** [comment]
Could you give me a usecase: Is this from the same thread, or from a remote thread?

**Comment by liamwhite** [comment]
@merryhime the usecase is that yuzu wants to possibly signal halts from either the running thread itself (as in from a callback) or a different thread to interrupt dynarmic, and then to clear the halt from only the targeted thread itself, never another thread.

**Comment by liamwhite** [comment]
Done

**Pull request merged**
